### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by QichaoChen** [ganfra/MaterialSpinner#1]
when import project to my AS and try to run sample I got error message below:

```java
java.lang.RuntimeException: Unable to start activity ComponentInfo{fr.ganfra.materialspinner.sample/fr.ganfra.materialspinner.sample.MainActivity}: java.lang.IllegalArgumentException: Spinner adapter view type count must be 1
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: Spinner adapter view type count must be 1
            at android.widget.Spinner.setAdapter(Spinner.java:439)
            at fr.ganfra.materialspinner.MaterialSpinner.setAdapter(MaterialSpinner.java:597)
            at fr.ganfra.materialspinner.sample.MainActivity.initSpinnerHintAndFloatingLabel(MainActivity.java:46)
            at fr.ganfra.materialspinner.sample.MainActivity.onCreate(MainActivity.java:37)
            at android.app.Activity.performCreate(Activity.java:5990)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

**Comment by ganfra** [comment]
Do you test it on Lollipop device ?
It seems to be a known issue : https://code.google.com/p/android/issues/detail?id=79011
