### ISSUE TITLE
MaterialSpinner vs Espresso

### ISSUE THREAD

**Issue by Daard** [ganfra/MaterialSpinner#63]
I am trying to write instrumentation tests for my app. But I have faced strange problem when I run my tests.

android.support.test.espresso.PerformException: Error performing 'load adapter data' on view 'is assignable from class: class android.widget.AdapterView'.
at android.support.test.espresso.PerformException$Builder.build(PerformException.java:83)
at android.support.test.espresso.base.DefaultFailureHandler.getUserFriendlyError(DefaultFailureHandler.java:70)
at android.support.test.espresso.base.DefaultFailureHandler.handle(DefaultFailureHandler.java:53)
at android.support.test.espresso.ViewInteraction.runSynchronouslyOnUiThread(ViewInteraction.java:184)
at android.support.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:115)
at android.support.test.espresso.ViewInteraction.perform(ViewInteraction.java:87)
at android.support.test.espresso.DataInteraction.load(DataInteraction.java:151)
at android.support.test.espresso.DataInteraction.perform(DataInteraction.java:128)

at project.ActivityTest.test2withoutSeason(EditAgroOperationActivityTest.java:54) <------

And here is code:

@Test
    public void test2withoutSeason() {
       onView(withId(R.id.operation_status_spinner)).
              check(matches(isAssignableFrom(AdapterView.class)));
        onView(withId(R.id.operation_status_spinner)).perform(click());
        onData(allOf(instanceOf(String.class), is(R.string.planned))).perform(click()); <---------
    }

So Espresso tries to check that MaterialSpinner is assignable from AdapterView when performing load and throws exception. 

How can this be if    check(matches(isAssignableFrom(AdapterView.class))) runs correctly?

**Comment by Daard** [comment]
I replaced Espresso code with this
  onData(anything()).inAdapterView(withId(R.id.operation_status_spinner)).atPosition(2).perform(click());
and it works fine

**Comment by mdumrauf** [comment]
Thanks for the example @Daard. Closing since I understand it was a bug in Espresso and you managed to solve it.
