### ISSUE TITLE
This is the exception i got on programatically setting spinner item in some spinner and some other works fine

### ISSUE THREAD

**Issue by TheGreat0004** [ganfra/MaterialSpinner#65]
java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.AbsListView$LayoutParams
                                                                    at android.widget.ListView.setupChild(ListView.java:1826)
                                                                    at android.widget.ListView.makeAndAddView(ListView.java:1793)
                                                                    at android.widget.ListView.fillUp(ListView.java:725)
                                                                    at android.widget.ListView.correctTooHigh(ListView.java:1414)
                                                                    at android.widget.ListView.fillSpecific(ListView.java:1352)
                                                                    at android.widget.ListView.layoutChildren(ListView.java:1620)
                                                                    at android.widget.AbsListView.onLayout(AbsListView.java:2087)
                                                                    at android.view.View.layout(View.java:14817)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                    at android.view.View.layout(View.java:14817)
                                                                    at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
                                                                    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
                                                                    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                    at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                    at android.os.Handler.handleCallback(Handler.java:733)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:5001)
                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by mdumrauf** [comment]
Please provide a code sample on how you are setting the adapter. The ClassCastException is very generic in this case.
