### ISSUE TITLE
Crash on empty array data set

### ISSUE THREAD

**Issue by LisitaEugen** [ganfra/MaterialSpinner#68]
Hello, on empty array set got that crash:
 java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                                  at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:394)
                                                                  at android.widget.ArrayAdapter.getDropDownView(ArrayAdapter.java:415)
                                                                  at fr.ganfra.materialspinner.MaterialSpinner$HintAdapter.buildView(MaterialSpinner.java:786)
                                                                  at fr.ganfra.materialspinner.MaterialSpinner$HintAdapter.getDropDownView(MaterialSpinner.java:774)
                                                                  at android.widget.Spinner$DropDownAdapter.getDropDownView(Spinner.java:878)
                                                                  at android.widget.Spinner$DropDownAdapter.getView(Spinner.java:874)
                                                                  at android.widget.Spinner.measureContentWidth(Spinner.java:759)
                                                                  at android.widget.Spinner$DropdownPopup.computeContentWidth(Spinner.java:1109)
                                                                  at android.widget.Spinner$DropdownPopup.show(Spinner.java:1135)
                                                                  at android.widget.Spinner.performClick(Spinner.java:683)
                                                                  at android.view.View$PerformClick.run(View.java:19866)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:135)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:372)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by mdumrauf** [comment]
Please check the sample introduced in #102
