### ISSUE TITLE
 Error inflating class fr.ganfra.materialspinner.MaterialSpinner

### ISSUE THREAD

**Issue by drayan85** [ganfra/MaterialSpinner#73]
08-25 17:06:17.635 21412-21412/com.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: com.sample, PID: 21412
                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sample/com.sample.NewDiscussionActivity}: android.view.InflateException: Binary XML file line #187: Binary XML file line #187: Error inflating class fr.ganfra.materialspinner.MaterialSpinner
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                              Caused by: android.view.InflateException: Binary XML file line #187: Binary XML file line #187: Error inflating class fr.ganfra.materialspinner.MaterialSpinner
                                                              Caused by: android.view.InflateException: Binary XML file line #187: Error inflating class fr.ganfra.materialspinner.MaterialSpinner
                                                              Caused by: java.lang.ClassNotFoundException: Didn't find class "fr.ganfra.materialspinner.MaterialSpinner" on path: DexPathList[[zip file "/data/app/com.sample-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sample-1/lib/arm64, /system/lib64, /vendor/lib64]]
                                                                 at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                 at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:609)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
                                                                 at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:280)
                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                 at com.sample.NewDiscussionActivity.onCreate(NewDiscussionActivity.java:26)
                                                                 at android.app.Activity.performCreate(Activity.java:6664)
                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by imranhakeem** [comment]
@drayan85 How did you solved this issue?

**Comment by drayan85** [comment]
In your, Gradle add the below lines
`// Enabling multiDex support.
  multiDexEnabled true`


`compile 'com.android.support:multidex:1.0.1'`

**Comment by timbaev** [comment]
There is other solution? Enabling multiDex support didn't help

**Comment by drayan85** [comment]
@timbaev Clean build also didn't work after adding the multidex ?

**Comment by timbaev** [comment]
@drayan85 yes

**Comment by Ragulsekar** [comment]
@timbaev  I,m also facing same issue. Have you fixed? If so, please help me.

**Comment by drayan85** [comment]
@timbaev, could you please post your layout XML here?

**Comment by Ragulsekar** [comment]
@drayan85, can u please help me to solve this issue.

**Comment by drayan85** [comment]
@Ragulsekar paste your layout xml here

**Comment by Ragulsekar** [comment]
@drayan85, this is my layout

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:ls="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/white"
    android:orientation="vertical">

    <RelativeLayout
        android:id="@+id/layoutrel"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="@color/colorPrimary">

        <RelativeLayout
            android:id="@+id/backlay"
            android:layout_width="55dp"
            android:layout_height="40dp"
            android:layout_centerVertical="true">

            <ImageView
                android:id="@+id/back"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_centerInParent="true"
                android:src="@mipmap/back" />
        </RelativeLayout>

        <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:layout_weight="0.90"
            android:gravity="center"
            android:padding="10dp">

            <TextView
                android:id="@+id/title"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/fund_my_account"
                android:textAllCaps="true"
                android:textColor="#FFFFFF"
                android:textSize="16sp" />
        </LinearLayout>
    </RelativeLayout>

    <RelativeLayout
        android:id="@+id/ly_main"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_margin="16dp">

        <ImageView
            android:id="@+id/image"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_marginTop="20dp"
            android:src="@mipmap/makepayment"
            android:tint="@color/colorAccent" />

        <TextView
            android:id="@+id/tv_select_bank"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/image"
            android:layout_marginTop="20dp"
            android:text="@string/select_your_bank"
            android:textColor="@color/colorAccent"
            android:textSize="20sp" />

        <LinearLayout
            android:id="@+id/spinner_layout"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/tv_select_bank"
            android:layout_marginTop="20dp"
            android:background="@drawable/green_bg"
            android:orientation="vertical">

            <fr.ganfra.materialspinner.MaterialSpinner
                android:id="@+id/spinner_bank"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:ms_alignLabels="false"
                app:ms_arrowSize="16dp"
                app:ms_enableErrorLabel="false"
                app:ms_enableFloatingLabel="false"
                app:ms_highlightColor="@color/colorAccent"
                app:ms_hint="hint"
                app:ms_hintColor="@color/white"
                app:ms_multiline="false"
                app:ms_thickness="2dp"
                app:ms_typeface="typeface.ttf" />
            
        </LinearLayout>

        <EditText
            android:id="@+id/et_amount"
            android:layout_width="match_parent"
            android:layout_height="50dp"
            android:layout_below="@+id/spinner_layout"
            android:layout_marginTop="40dp"
            android:background="@drawable/green_bg"
            android:gravity="center"
            android:hint="@string/enter_the_amount"
            android:inputType="numberDecimal"
            android:maxLines="1"
            android:textColor="@android:color/white"
            android:textColorHint="#ffffff"
            android:textSize="20sp" />

        <Button
            android:id="@+id/btn_review"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_below="@+id/et_amount"
            android:layout_marginTop="40dip"
            android:background="@mipmap/btn_dark_grey"
            android:text="@string/review"
            android:textColor="#FFFFFF"
            android:textSize="20sp" />
    </RelativeLayout>

</LinearLayout>

**Comment by Ragulsekar** [comment]
@drayan85, these are support libraries 
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:design:25.3.1'
   compile 'com.android.support:multidex:1.0.1'
    compile 'com.android.support:cardview-v7:25.3.1'

**Comment by drayan85** [comment]
@Ragulsekar what is your root layout?

**Comment by drayan85** [comment]
@Ragulsekar could you please try the layout without modifying adding more elements?

```xml
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <LinearLayout
        android:id="@+id/layoutrel"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="8dp"
        android:layout_marginTop="8dp"
        android:background="@color/colorPrimary"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/back"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:src="@mipmap/back" />

        <TextView
            android:id="@+id/title"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginRight="32dp"
            android:layout_weight="1"
            android:gravity="center"
            android:text="@string/fund_my_account"
            android:textAllCaps="true"
            android:textAppearance="@style/TextAppearance.AppCompat.Subhead"
            android:textColor="@android:color/white"
            tools:text="Fund My Account" />

    </LinearLayout>


    <ImageView
        android:id="@+id/image"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="20dp"
        android:src="@mipmap/makepayment"
        android:tint="@color/colorAccent" />

    <TextView
        android:id="@+id/tv_select_bank"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="20dp"
        android:textAppearance="@style/TextAppearance.AppCompat.Title"
        android:text="@string/select_your_bank"
        android:textColor="@color/colorAccent"
        tools:text="Select Your Account" />

    <fr.ganfra.materialspinner.MaterialSpinner
        android:id="@+id/spinner_bank"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginLeft="16dp"
        android:layout_marginRight="16dp"
        android:layout_marginTop="20dp"
        app:ms_alignLabels="false"
        app:ms_arrowSize="16dp"
        app:ms_enableErrorLabel="false"
        app:ms_enableFloatingLabel="false"
        app:ms_highlightColor="@color/colorAccent"
        app:ms_hint="hint"
        app:ms_hintColor="@android:color/white"
        app:ms_multiline="false"
        app:ms_thickness="2dp"
        app:ms_typeface="typeface.ttf" />

    <EditText
        android:id="@+id/et_amount"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="40dp"
        android:background="@drawable/green_bg"
        android:gravity="center"
        android:hint="@string/enter_the_amount"
        android:inputType="numberDecimal"
        android:maxLines="1"
        android:padding="16dp"
        android:textAppearance="@style/TextAppearance.AppCompat.Title"
        android:textColor="@android:color/white"
        android:textColorHint="@android:color/white" />

    <Button
        android:id="@+id/btn_review"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="center_horizontal"
        android:layout_marginTop="48dp"
        android:background="@mipmap/btn_dark_grey"
        android:text="@string/review"
        android:textAppearance="@style/TextAppearance.AppCompat.Title"
        android:textColor="@android:color/white"
        tools:text="Review" />

</LinearLayout>
```

**Comment by Ragulsekar** [comment]
@drayan85, I have tried like you said, view is working good, but item click is not taking. How to get the selected item?

**Comment by drayan85** [comment]
`app:ms_enableFloatingLabel="false"` change to `app:ms_enableFloatingLabel="true"`

**Comment by Ragulsekar** [comment]
@drayan85, I'm using setOnItemSelectedListener only, even thought  not able to get the selected item.

**Comment by drayan85** [comment]
what is the crash you are getting now? is it related MaterialSpinner?

**Comment by Ragulsekar** [comment]
@drayan85, I fixed crash, now  setOnItemSelectedListener is not working, not able to get the selected item

**Comment by drayan85** [comment]
What do you mean by not be able to select? After a select text from the list, still, the hint is visible in MaterialSpinner?

**Comment by Ragulsekar** [comment]
@drayan85, If I using both hint and setOnItemSelectedListener, app is crash.

**Comment by drayan85** [comment]
@Ragulsekar you are not providing not enough details or stack trace and alternatively, you can ask this question in StackOverflow, you may get an answer.

**Comment by Ragulsekar** [comment]
@drayan85 Thank You.

**Comment by amirdora** [comment]
I got the same error, i removed < app:ms_typeface="typeface.ttf"> it resolved the issue but the spinner looks ugly. 👎 this is buggy fix it

**Comment by kishanverma26** [comment]
> I got the same error, I removed < app:ms_typeface="typeface.ttf"> it resolved the issue but the spinner looks ugly. 👎 please fix the bug.

this one sort my problem thanks @amirdora
