### ISSUE TITLE
setError throws exception

### ISSUE THREAD

**Issue by needo2** [ganfra/MaterialSpinner#82]
```
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.lang.reflect.Method.invoke(java.lang.Object, java.lang.Object[])' on a null object reference
  at com.nineoldandroids.animation.PropertyValuesHolder.setupSetterAndGetter(PropertyValuesHolder.java:533)
  at com.nineoldandroids.animation.ObjectAnimator.initAnimation(ObjectAnimator.java:410)
  at com.nineoldandroids.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:538)
  at com.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:928)
  at com.nineoldandroids.animation.ValueAnimator.start(ValueAnimator.java:951)
  at com.nineoldandroids.animation.ObjectAnimator.start(ObjectAnimator.java:385)
  at fr.ganfra.materialspinner.MaterialSpinner.startErrorMultilineAnimator(MaterialSpinner.java:321)
  at fr.ganfra.materialspinner.MaterialSpinner.setError(MaterialSpinner.java:617)
```

**Comment by mdumrauf** [comment]
Not happening anymore :)
