### ISSUE TITLE
Runtime exception using calligraphy

### ISSUE THREAD

**Issue by pcegarra** [ganfra/MaterialSpinner#87]
I cant inflate this layout using calligraphy library for custom default fonts:

 java.lang.RuntimeException: Unable to start activity }: android.view.InflateException: Binary XML file line #20: Error inflating class fr.ganfra.materialspinner.MaterialSpinner
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2339)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2413)
                                                                      at android.app.ActivityThread.access$800(ActivityThread.java:155)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1317)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:135)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5343)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
                                                                   Caused by: android.view.InflateException: Binary XML file line #20: Error inflating class fr.ganfra.materialspinner.MaterialSpinner
                                                                      at android.view.LayoutInflater.createView(LayoutInflater.java:633)
                                                                      at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.createCustomViewInternal(CalligraphyLayoutInflater.java:211)
                                                                      at uk.co.chrisjenx.calligraphy.CalligraphyLayoutInflater.access$000(CalligraphyLayoutInflater.java:20)

**Comment by mdumrauf** [comment]
Can you please provide a code sample on how you are using it?
