### ISSUE TITLE
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

### ISSUE THREAD

**Issue by michaelbukachi** [ganfra/MaterialSpinner#93]
So I got this crash yesterday from one of my testers:
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:337)
       at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:390)
       at android.widget.ArrayAdapter.getView(ArrayAdapter.java:362)
       at fr.ganfra.materialspinner.MaterialSpinner$HintAdapter.buildView(MaterialSpinner.java:786)
       at fr.ganfra.materialspinner.MaterialSpinner$HintAdapter.getView(MaterialSpinner.java:769)
       at android.widget.Spinner.makeView(Spinner.java:593)
       at android.widget.Spinner.layout(Spinner.java:541)
       at android.widget.Spinner.onLayout(Spinner.java:503)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1160)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:437)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1888)
       at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1742)
       at android.widget.LinearLayout.onLayout(LinearLayout.java:1651)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:515)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:450)
       at android.view.View.layout(View.java:15140)
       at android.view.ViewGroup.layout(ViewGroup.java:4866)
       at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2336)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2042)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1208)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6274)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:788)
       at android.view.Choreographer.doCallbacks(Choreographer.java:591)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:774)
       at android.os.Handler.handleCallback(Handler.java:808)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
Does the spinner support empty lists?

**Comment by mdumrauf** [comment]
It does support empty lists. Can you provide a code example for this crash?

**Comment by mdumrauf** [comment]
Duplicate https://github.com/ganfra/MaterialSpinner/issues/68
